recipe: default.v1
language: zh

pipeline:
  - name: "JiebaTokenizer"
    dictionary_path: ../examples/chinesebot/dictionary
  - name: "LanguageModelFeaturizer"
    model_name: bert
    model_weights: bert-base-chinese
  - name: "DIETClassifier"
    entity_recognition: True
    epochs: 150
  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
    epochs: 100
    retrieval_intent: chitchat

policies:
  - name: TEDPolicy
#    max_history: 5
    epochs: 100
  - name: MemoizationPolicy
  - name: RulePolicy
