recipe: default.v1
language: en

pipeline:
  - name: "SpacyNLP"
    model: "en_core_web_md"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "DIETClassifier"
    entity_recognition: False
    epochs: 50
  - name: "ResponseSelector"
    epochs: 100
    retrieval_intent: chitchat

policies:
  - name: TEDPolicy
#    max_history: 5
    epochs: 100
  - name: MemoizationPolicy
  - name: RulePolicy
